-- =============================================
-- TEMPORARILY DISABLE RLS FOR DATA IMPORT
-- Run this BEFORE importing data
-- =============================================

ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.services DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_logos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_form_fields DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.home_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.home_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_values DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_timeline DISABLE ROW LEVEL SECURITY;
